### ISSUE TITLE
Feedback Research question

### ISSUE THREAD

**Issue by Vuurvos1** [RowinRuizendaal/functional-programming#1]
## Research question

One of your questions is by which garages you can pay by card in 2020, are you also going to look for data before 2020 to see if there is an increase in places where you can only pay by card.

Maybe there are some rare or weird payment methods for parking garages interesting to note.

## Datasets needed
I think you have all the essential data you need. Maybe you can find some more interesting variables related to payment and money. Like in this dataset there is information about how expensive parking is: [Open-Data-Parkeren-TARIEFDEEL](https://opendata.rdw.nl/Parkeren/Open-Data-Parkeren-TARIEFDEEL/534e-5vdg)

## Assumptions

Some assumptions I made when reading:
- There are more places where you can only pay by card than by cash
- Parking spots closer to the city centre have more payment options and are more expensive than ones further away
 
Keep it up and keep on rolling 🤠🙃🙂

**Comment by RowinRuizendaal** [comment]
@Vuurvos1,
Thanks for your feedback.
