### ISSUE TITLE
Peer-review FP 28/10/2020 by RalfZ

### ISSUE THREAD

**Issue by ralfz123** [RowinRuizendaal/functional-programming#2]
_How can you pay at a specific parking garage (by card, coins, bank**b**otes, visa etc.)_ 
bank**b**otes => bank**n**otes :)

**Onderzoeksvraag: _How can you pay at a specific parking garage?_**
Onderzoeksvraag is erg helder en lekker breed. Je kunt dus allerlei kanten op met deze vraag.
Waarover wil je specifiek nog meer weten? Ik zou namelijk wel een richting (focus) kiezen binnen je vraag, dan kan je daar namelijk meer naartoe werken 👍 .

**(Sub)Vragen die jouw onderzoeksvraag bij mij oproept:**
- Zijn er parkeergebieden waar je met cryptocoins kunt betalen?
- Hoe ver liggen de betaalautomaten uit elkaar in een bepaald parkeergebied?
- Zijn de betaalautomaten rolstoel-proof (hoogte van automaten)?
- Waar kun je nog wèl met contant geld betalen bij een betaalautomaat?
- Hoe zijn de betaalmethodes (contant, pin) verdeeld over de stad? Centrum meer pin mogelijkheden dan buiten het centrum?

**Data die je nog zou kunnen gebruiken:**
- Locatie van betaalautomaten (i don’t know of deze data er is?)
- Prijzen per parkeergebied (--> heeft de omgeving (centrum, A'dam Oost) daar invloed op?)

Ziet er overall goed uit en netjes!

by @ralfz123

**Comment by RowinRuizendaal** [comment]
@ralfz123,

Thanks for the feedback, this really helped me!
