### ISSUE TITLE
Peer-review Repo - 29/10/2020

### ISSUE THREAD

**Issue by ralfz123** [RowinRuizendaal/functional-programming#3]
**Scan the repo+readme**
- _This is the reprository for cleaning the datavisualistaion students dataset formated in JSON,_
-> Ik zou dit About-kopje in je Readme even veranderen naar de Vk opdracht of dat erbij zetten. Leg uit wat de Vk opdracht inhoudt.

- Beschrijf je concept, wat wil je maken?
- En heb je al ideeen daarover (schets/lo-fi viz?)?
- **link** to most interesting functional pattern?
- Waar zijn je gebruikte bronnen en credits to?

**Read the wiki**
- Nice code over hoe je bezig bent met opschonen van de Survey data .
- Goede debriefing aanwezig.
- Nette first dataset insights pagina.
- Waar is het transforming process ?

**Read the code linked in the wiki**
- Gebruik je een formatter voor je code? Ik vind het [soms](https://github.com/RowinRuizendaal/functional-programming/wiki/datasets#attempt-3) moeilijk om overzicht te hebben in je code.
- Ben je al bezig geweest met code van het data opschonen van het RDW? Laat dit dan zien in je Wiki en welke FP patterns je dan toepast in je code.
(- Je code in het project zelf is erg netjes en goed gestructureerd. Zorg dat je consistentie hebt in elke file.)
- Gebruik iets meer code comments, waarin je uitlegt wat dat code block doet.

**Tops:**
- Nette Readme; Duidelijke volgorde en mooi dat je het install-proces heb verwerkt.
- Strakke code in je project--> je bent al advanced zo te zien
- Lekker op weg met zowel documenteren als met coderen, nice!

____
Goed op weg en je bent lekker bezig man,
Succes met het verwerken van de feedback en als je vragen hebt, stel ze!

🚀 🚀 🚀 🚀 🚀 🚀 🚀 🚀

**Comment by RowinRuizendaal** [comment]
Thanks, merk dat ik deze issue niet gesloten had lol, beter laat dan nooit ;)

Groetjes 🙋‍♂️
