### ISSUE TITLE
Feedback hoofdvraag

### ISSUE THREAD

**Issue by chelseadoeleman** [RowinRuizendaal/functional-programming#4]
Hi Rowin! 

Goede hoofdvraag met duidelijke deelvragen! 👍 Als je misschien nog aan de slag wil gaan met een externe dataset zou je misschien ook nog kunnen kijken in welke buurt (of steden, dan heb je niet per se nog een externe dataset nodig😉) bijvoorbeeld meer met een bepaalde betaalmethode wordt betaald.

**Comment by RowinRuizendaal** [comment]
Hoi @chelseadoeleman,

Nog bedankt voor je feedback ;) ik kwam er dus net achter dat ik hier nooit op gereageerd had of het gesloten had. Dus bij deze: nogmaals bedankt voor je suggestie 
🙋‍♂️
